# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84763ef12da3d88a5b69725119ed6f2a59744c5bfcda3f12c74d3f74ab9235121711d2bea97afa95db96f6bf9a65dbf9fe1d3eb78adb17caff512f35acb9807f

test:
  secret_key_base: 411095e1a51793dd7e60086b4066323c1220241426b1d52ca5fce61543b10c5862f64d2f6bdd765e8ca88d3c6fe6c15f0910c3bdf09b0da439797a1395c939cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
